#include "render/EmojiMap.h"

namespace conduit::render {

// hand-curated mapping of slack emoji names to UTF-8 byte sequences.
// yes, i typed all of these out. no, i'm not proud of it.
// some emoji have multiple aliases in slack (thumbsup/+1, laughing/joy, etc)
// so we map all the common variants because slack users can't agree on names.

const std::unordered_map<std::string, std::string>& getEmojiMap() {
    static const std::unordered_map<std::string, std::string> map = {
        // faces - the bread and butter of passive-aggressive workplace communication
        {"grinning",             "\xF0\x9F\x98\x80"},
        {"smile",                "\xF0\x9F\x98\x84"},
        {"smiley",               "\xF0\x9F\x98\x84"},
        {"laughing",             "\xF0\x9F\x98\x82"},
        {"joy",                  "\xF0\x9F\x98\x82"},
        {"rofl",                 "\xF0\x9F\xA4\xA3"},
        {"wink",                 "\xF0\x9F\x98\x89"},
        {"blush",                "\xF0\x9F\x98\x8A"},
        {"innocent",             "\xF0\x9F\x98\x87"},
        {"slightly_smiling_face","\xF0\x9F\x99\x82"},
        {"upside_down_face",     "\xF0\x9F\x99\x83"},
        {"sweat_smile",          "\xF0\x9F\x98\x85"},
        {"relieved",             "\xF0\x9F\x98\x8C"},
        {"heart_eyes",           "\xF0\x9F\x98\x8D"},
        {"kissing_heart",        "\xF0\x9F\x98\x98"},
        {"yum",                  "\xF0\x9F\x98\x8B"},
        {"stuck_out_tongue",     "\xF0\x9F\x98\x9B"},
        {"stuck_out_tongue_winking_eye", "\xF0\x9F\x98\x9C"},
        {"stuck_out_tongue_closed_eyes", "\xF0\x9F\x98\x9D"},
        {"sunglasses",           "\xF0\x9F\x98\x8E"},
        {"nerd_face",            "\xF0\x9F\xA4\x93"},
        {"thinking_face",        "\xF0\x9F\xA4\x94"},
        {"thinking",             "\xF0\x9F\xA4\x94"},
        {"confused",             "\xF0\x9F\x98\x95"},
        {"worried",              "\xF0\x9F\x98\x9F"},
        {"frowning",             "\xF0\x9F\x98\xA6"},
        {"angry",                "\xF0\x9F\x98\xA0"},
        {"rage",                 "\xF0\x9F\x98\xA1"},
        {"cry",                  "\xF0\x9F\x98\xA2"},
        {"sob",                  "\xF0\x9F\x98\xAD"},
        {"scream",               "\xF0\x9F\x98\xB1"},
        {"fearful",              "\xF0\x9F\x98\xA8"},
        {"cold_sweat",           "\xF0\x9F\x98\xB0"},
        {"hushed",               "\xF0\x9F\x98\xAF"},
        {"flushed",              "\xF0\x9F\x98\xB3"},
        {"sleeping",             "\xF0\x9F\x98\xB4"},
        {"grimacing",            "\xF0\x9F\x98\xAC"},
        {"expressionless",       "\xF0\x9F\x98\x91"},
        {"unamused",             "\xF0\x9F\x98\x92"},
        {"roll_eyes",            "\xF0\x9F\x99\x84"},
        {"face_with_hand_over_mouth", "\xF0\x9F\xA4\xAD"},
        {"shushing_face",        "\xF0\x9F\xA4\xAB"},
        {"zipper_mouth_face",    "\xF0\x9F\xA4\x90"},
        {"money_mouth_face",     "\xF0\x9F\xA4\x91"},
        {"hugging_face",         "\xF0\x9F\xA4\x97"},
        {"smirk",                "\xF0\x9F\x98\x8F"},
        {"pensive",              "\xF0\x9F\x98\x94"},
        {"disappointed",         "\xF0\x9F\x98\x9E"},
        {"persevere",            "\xF0\x9F\x98\xA3"},
        {"triumph",              "\xF0\x9F\x98\xA4"},
        {"face_palm",            "\xF0\x9F\xA4\xA6"},
        {"shrug",                "\xF0\x9F\xA4\xB7"},
        {"robot_face",           "\xF0\x9F\xA4\x96"},

        // hands - for when words aren't enough
        {"thumbsup",             "\xF0\x9F\x91\x8D"},
        {"+1",                   "\xF0\x9F\x91\x8D"},
        {"thumbsdown",           "\xF0\x9F\x91\x8E"},
        {"-1",                   "\xF0\x9F\x91\x8E"},
        {"wave",                 "\xF0\x9F\x91\x8B"},
        {"raised_hands",         "\xF0\x9F\x99\x8C"},
        {"clap",                 "\xF0\x9F\x91\x8F"},
        {"ok_hand",              "\xF0\x9F\x91\x8C"},
        {"point_up",             "\xF0\x9F\x91\x86"},
        {"point_down",           "\xF0\x9F\x91\x87"},
        {"point_left",           "\xF0\x9F\x91\x88"},
        {"point_right",          "\xF0\x9F\x91\x89"},
        {"muscle",               "\xF0\x9F\x92\xAA"},
        {"pray",                 "\xF0\x9F\x99\x8F"},
        {"handshake",            "\xF0\x9F\xA4\x9D"},
        {"crossed_fingers",      "\xF0\x9F\xA4\x9E"},
        {"v",                    "\xE2\x9C\x8C\xEF\xB8\x8F"},
        {"metal",                "\xF0\x9F\xA4\x98"},
        {"call_me_hand",         "\xF0\x9F\xA4\x99"},
        {"writing_hand",         "\xE2\x9C\x8D\xEF\xB8\x8F"},
        {"open_hands",           "\xF0\x9F\x91\x90"},
        {"raised_hand",          "\xE2\x9C\x8B"},
        {"vulcan_salute",        "\xF0\x9F\x96\x96"},

        // hearts and emotions
        {"heart",                "\xE2\x9D\xA4\xEF\xB8\x8F"},
        {"orange_heart",         "\xF0\x9F\xA7\xA1"},
        {"yellow_heart",         "\xF0\x9F\x92\x9B"},
        {"green_heart",          "\xF0\x9F\x92\x9A"},
        {"blue_heart",           "\xF0\x9F\x92\x99"},
        {"purple_heart",         "\xF0\x9F\x92\x9C"},
        {"black_heart",          "\xF0\x9F\x96\xA4"},
        {"broken_heart",         "\xF0\x9F\x92\x94"},
        {"heartpulse",           "\xF0\x9F\x92\x97"},
        {"sparkling_heart",      "\xF0\x9F\x92\x96"},

        // reactions that say "i acknowledge your message" in corporate-speak
        {"fire",                 "\xF0\x9F\x94\xA5"},
        {"eyes",                 "\xF0\x9F\x91\x80"},
        {"rocket",               "\xF0\x9F\x9A\x80"},
        {"tada",                 "\xF0\x9F\x8E\x89"},
        {"party_popper",         "\xF0\x9F\x8E\x89"},
        {"confetti_ball",        "\xF0\x9F\x8E\x8A"},
        {"100",                  "\xF0\x9F\x92\xAF"},
        {"skull",                "\xF0\x9F\x92\x80"},
        {"poop",                 "\xF0\x9F\x92\xA9"},
        {"ghost",                "\xF0\x9F\x91\xBB"},
        {"alien",                "\xF0\x9F\x91\xBD"},
        {"boom",                 "\xF0\x9F\x92\xA5"},
        {"collision",            "\xF0\x9F\x92\xA5"},
        {"sparkles",             "\xE2\x9C\xA8"},
        {"star",                 "\xE2\xAD\x90"},
        {"star2",                "\xF0\x9F\x8C\x9F"},
        {"zap",                  "\xE2\x9A\xA1"},
        {"rainbow",              "\xF0\x9F\x8C\x88"},
        {"sun_with_face",        "\xF0\x9F\x8C\x9E"},

        // checkmarks and X's - the currency of code review
        {"white_check_mark",     "\xE2\x9C\x85"},
        {"heavy_check_mark",     "\xE2\x9C\x94\xEF\xB8\x8F"},
        {"ballot_box_with_check","\xE2\x98\x91\xEF\xB8\x8F"},
        {"x",                    "\xE2\x9D\x8C"},
        {"negative_squared_cross_mark", "\xE2\x9D\x8E"},

        // warning signs for when production is on fire
        {"warning",              "\xE2\x9A\xA0\xEF\xB8\x8F"},
        {"rotating_light",       "\xF0\x9F\x9A\xA8"},
        {"no_entry",             "\xF0\x9F\x9A\xAB"},
        {"stop_sign",            "\xF0\x9F\x9B\x91"},
        {"construction",         "\xF0\x9F\x9A\xA7"},

        // colored circles - surprisingly useful in standup notes
        {"red_circle",           "\xF0\x9F\x94\xB4"},
        {"large_green_circle",   "\xF0\x9F\x9F\xA2"},
        {"green_circle",         "\xF0\x9F\x9F\xA2"},
        {"large_blue_circle",    "\xF0\x9F\x94\xB5"},
        {"blue_circle",          "\xF0\x9F\x94\xB5"},
        {"white_circle",         "\xE2\x9A\xAA"},
        {"black_circle",         "\xE2\x9A\xAB"},
        {"large_orange_circle",  "\xF0\x9F\x9F\xA0"},
        {"large_yellow_circle",  "\xF0\x9F\x9F\xA1"},
        {"large_purple_circle",  "\xF0\x9F\x9F\xA3"},
        {"large_brown_circle",   "\xF0\x9F\x9F\xA4"},

        // objects - the misc drawer of emoji
        {"speech_balloon",       "\xF0\x9F\x92\xAC"},
        {"thought_balloon",      "\xF0\x9F\x92\xAD"},
        {"bulb",                 "\xF0\x9F\x92\xA1"},
        {"memo",                 "\xF0\x9F\x93\x9D"},
        {"pencil",               "\xE2\x9C\x8F\xEF\xB8\x8F"},
        {"hammer",               "\xF0\x9F\x94\xA8"},
        {"wrench",               "\xF0\x9F\x94\xA7"},
        {"gear",                 "\xE2\x9A\x99\xEF\xB8\x8F"},
        {"lock",                 "\xF0\x9F\x94\x92"},
        {"unlock",               "\xF0\x9F\x94\x93"},
        {"key",                  "\xF0\x9F\x94\x91"},
        {"mag",                  "\xF0\x9F\x94\x8D"},
        {"mag_right",            "\xF0\x9F\x94\x8E"},
        {"link",                 "\xF0\x9F\x94\x97"},
        {"paperclip",            "\xF0\x9F\x93\x8E"},
        {"email",                "\xF0\x9F\x93\xA7"},
        {"phone",                "\xF0\x9F\x93\xB1"},
        {"computer",             "\xF0\x9F\x92\xBB"},
        {"desktop_computer",     "\xF0\x9F\x96\xA5\xEF\xB8\x8F"},
        {"keyboard",             "\xE2\x8C\xA8\xEF\xB8\x8F"},
        {"calendar",             "\xF0\x9F\x93\x85"},
        {"clock",                "\xF0\x9F\x95\x90"},
        {"hourglass",            "\xE2\x8F\xB3"},
        {"hourglass_flowing_sand","\xE2\x8F\xB3"},
        {"money_bag",            "\xF0\x9F\x92\xB0"},
        {"dollar",               "\xF0\x9F\x92\xB5"},
        {"chart",                "\xF0\x9F\x93\x8A"},
        {"chart_with_upwards_trend",   "\xF0\x9F\x93\x88"},
        {"chart_with_downwards_trend", "\xF0\x9F\x93\x89"},
        {"bar_chart",            "\xF0\x9F\x93\x8A"},
        {"clipboard",            "\xF0\x9F\x93\x8B"},
        {"pushpin",              "\xF0\x9F\x93\x8C"},
        {"round_pushpin",        "\xF0\x9F\x93\x8D"},
        {"triangular_flag_on_post", "\xF0\x9F\x9A\xA9"},
        {"checkered_flag",       "\xF0\x9F\x8F\x81"},
        {"bell",                 "\xF0\x9F\x94\x94"},
        {"no_bell",              "\xF0\x9F\x94\x95"},
        {"loudspeaker",          "\xF0\x9F\x93\xA2"},
        {"mega",                 "\xF0\x9F\x93\xA3"},
        {"package",              "\xF0\x9F\x93\xA6"},
        {"inbox_tray",           "\xF0\x9F\x93\xA5"},
        {"outbox_tray",          "\xF0\x9F\x93\xA4"},
        {"bookmark",             "\xF0\x9F\x94\x96"},
        {"books",                "\xF0\x9F\x93\x9A"},
        {"file_folder",          "\xF0\x9F\x93\x81"},
        {"wastebasket",          "\xF0\x9F\x97\x91\xEF\xB8\x8F"},

        // trophies and medals - for when someone deploys without breaking prod
        {"trophy",               "\xF0\x9F\x8F\x86"},
        {"medal",                "\xF0\x9F\x8F\x85"},
        {"first_place_medal",    "\xF0\x9F\xA5\x87"},
        {"second_place_medal",   "\xF0\x9F\xA5\x88"},
        {"third_place_medal",    "\xF0\x9F\xA5\x89"},
        {"crown",                "\xF0\x9F\x91\x91"},
        {"gem",                  "\xF0\x9F\x92\x8E"},

        // animals (because every slack workspace has these)
        {"see_no_evil",          "\xF0\x9F\x99\x88"},
        {"hear_no_evil",         "\xF0\x9F\x99\x89"},
        {"speak_no_evil",        "\xF0\x9F\x99\x8A"},
        {"monkey_face",          "\xF0\x9F\x90\xB5"},
        {"dog",                  "\xF0\x9F\x90\x95"},
        {"dog2",                 "\xF0\x9F\x90\x95"},
        {"cat",                  "\xF0\x9F\x90\x88"},
        {"cat2",                 "\xF0\x9F\x90\x88"},
        {"snake",                "\xF0\x9F\x90\x8D"},
        {"bug",                  "\xF0\x9F\x90\x9B"},
        {"bee",                  "\xF0\x9F\x90\x9D"},
        {"honeybee",             "\xF0\x9F\x90\x9D"},
        {"butterfly",            "\xF0\x9F\xA6\x8B"},
        {"unicorn_face",         "\xF0\x9F\xA6\x84"},
        {"turtle",               "\xF0\x9F\x90\xA2"},
        {"octopus",              "\xF0\x9F\x90\x99"},
        {"penguin",              "\xF0\x9F\x90\xA7"},

        // food - the most opinionated category in any workspace
        {"pizza",                "\xF0\x9F\x8D\x95"},
        {"hamburger",            "\xF0\x9F\x8D\x94"},
        {"taco",                 "\xF0\x9F\x8C\xAE"},
        {"burrito",              "\xF0\x9F\x8C\xAF"},
        {"hot_pepper",           "\xF0\x9F\x8C\xB6\xEF\xB8\x8F"},
        {"avocado",              "\xF0\x9F\xA5\x91"},
        {"cookie",               "\xF0\x9F\x8D\xAA"},
        {"cake",                 "\xF0\x9F\x8E\x82"},
        {"birthday",             "\xF0\x9F\x8E\x82"},
        {"doughnut",             "\xF0\x9F\x8D\xA9"},
        {"ice_cream",            "\xF0\x9F\x8D\xA8"},
        {"popcorn",              "\xF0\x9F\x8D\xBF"},
        {"ramen",                "\xF0\x9F\x8D\x9C"},
        {"sushi",                "\xF0\x9F\x8D\xA3"},
        {"fries",                "\xF0\x9F\x8D\x9F"},

        // drinks - the fuel
        {"coffee",               "\xE2\x98\x95"},
        {"tea",                  "\xF0\x9F\x8D\xB5"},
        {"beer",                 "\xF0\x9F\x8D\xBA"},
        {"beers",                "\xF0\x9F\x8D\xBB"},
        {"wine_glass",           "\xF0\x9F\x8D\xB7"},
        {"cocktail",             "\xF0\x9F\x8D\xB8"},
        {"champagne",            "\xF0\x9F\x8D\xBE"},

        // celebrations and events
        {"christmas_tree",       "\xF0\x9F\x8E\x84"},
        {"gift",                 "\xF0\x9F\x8E\x81"},
        {"balloon",              "\xF0\x9F\x8E\x88"},
        {"jack_o_lantern",       "\xF0\x9F\x8E\x83"},
        {"fireworks",            "\xF0\x9F\x8E\x86"},

        // weather and nature
        {"sunny",                "\xE2\x98\x80\xEF\xB8\x8F"},
        {"cloud",                "\xE2\x98\x81\xEF\xB8\x8F"},
        {"umbrella",             "\xE2\x98\x82\xEF\xB8\x8F"},
        {"snowflake",            "\xE2\x9D\x84\xEF\xB8\x8F"},
        {"snowman",              "\xE2\x9B\x84"},
        {"thunder_cloud_and_rain","\xE2\x9B\x88\xEF\xB8\x8F"},
        {"partly_sunny",         "\xE2\x9B\x85"},
        {"ocean",                "\xF0\x9F\x8C\x8A"},
        {"earth_americas",       "\xF0\x9F\x8C\x8E"},
        {"globe_with_meridians", "\xF0\x9F\x8C\x90"},
        {"crescent_moon",        "\xF0\x9F\x8C\x99"},
        {"full_moon",            "\xF0\x9F\x8C\x95"},
        {"seedling",             "\xF0\x9F\x8C\xB1"},
        {"evergreen_tree",       "\xF0\x9F\x8C\xB2"},
        {"fallen_leaf",          "\xF0\x9F\x8D\x82"},
        {"maple_leaf",           "\xF0\x9F\x8D\x81"},
        {"cherry_blossom",       "\xF0\x9F\x8C\xB8"},
        {"rose",                 "\xF0\x9F\x8C\xB9"},
        {"sunflower",            "\xF0\x9F\x8C\xBB"},
        {"cactus",               "\xF0\x9F\x8C\xB5"},
        {"palm_tree",            "\xF0\x9F\x8C\xB4"},

        // transport and places
        {"car",                  "\xF0\x9F\x9A\x97"},
        {"airplane",             "\xE2\x9C\x88\xEF\xB8\x8F"},
        {"ship",                 "\xF0\x9F\x9A\xA2"},
        {"bike",                 "\xF0\x9F\x9A\xB2"},
        {"house",                "\xF0\x9F\x8F\xA0"},
        {"office",               "\xF0\x9F\x8F\xA2"},
        {"hospital",             "\xF0\x9F\x8F\xA5"},

        // flags (a few common ones)
        {"flag-us",              "\xF0\x9F\x87\xBA\xF0\x9F\x87\xB8"},
        {"flag-gb",              "\xF0\x9F\x87\xAC\xF0\x9F\x87\xA7"},
        {"flag-ca",              "\xF0\x9F\x87\xA8\xF0\x9F\x87\xA6"},
        {"flag-de",              "\xF0\x9F\x87\xA9\xF0\x9F\x87\xAA"},
        {"flag-fr",              "\xF0\x9F\x87\xAB\xF0\x9F\x87\xB7"},
        {"flag-jp",              "\xF0\x9F\x87\xAF\xF0\x9F\x87\xB5"},
        {"pirate_flag",          "\xF0\x9F\x8F\xB4\xE2\x80\x8D\xE2\x98\xA0\xEF\xB8\x8F"},

        // misc stuff that shows up in every engineering channel
        {"sos",                  "\xF0\x9F\x86\x98"},
        {"recycle",              "\xE2\x99\xBB\xEF\xB8\x8F"},
        {"trident",              "\xF0\x9F\x94\xB1"},
        {"infinity",             "\xE2\x99\xBE\xEF\xB8\x8F"},
        {"question",             "\xE2\x9D\x93"},
        {"exclamation",          "\xE2\x9D\x97"},
        {"interrobang",          "\xE2\x81\x89\xEF\xB8\x8F"},
        {"heavy_plus_sign",      "\xE2\x9E\x95"},
        {"heavy_minus_sign",     "\xE2\x9E\x96"},
        {"heavy_division_sign",  "\xE2\x9E\x97"},
        {"heavy_multiplication_x","\xE2\x9C\x96\xEF\xB8\x8F"},
        {"arrow_up",             "\xE2\xAC\x86\xEF\xB8\x8F"},
        {"arrow_down",           "\xE2\xAC\x87\xEF\xB8\x8F"},
        {"arrow_left",           "\xE2\xAC\x85\xEF\xB8\x8F"},
        {"arrow_right",          "\xE2\x9E\xA1\xEF\xB8\x8F"},
        {"new",                  "\xF0\x9F\x86\x95"},
        {"free",                 "\xF0\x9F\x86\x93"},
        {"up",                   "\xF0\x9F\x86\x99"},
        {"cool",                 "\xF0\x9F\x86\x92"},
        {"ok",                   "\xF0\x9F\x86\x97"},
        {"zzz",                  "\xF0\x9F\x92\xA4"},
        {"dizzy",                "\xF0\x9F\x92\xAB"},
        {"sweat_drops",          "\xF0\x9F\x92\xA6"},
        {"dash",                 "\xF0\x9F\x92\xA8"},
        {"hole",                 "\xF0\x9F\x95\xB3\xEF\xB8\x8F"},
        {"shield",               "\xF0\x9F\x9B\xA1\xEF\xB8\x8F"},
    };
    return map;
}

} // namespace conduit::render
